// SPDX-License-Identifier: AGPL-3.0-or-later

//! Band plans and channel maps.
//!
//! A "band plan" is a named list of channels; each channel has a frequency
//! and a short label.  The user picks a band plan, then a channel within it.
//!
//! **The plan data lives in `band_plans/*.toml`, not here** — each file is
//! one plan (`label` + `channels_khz`), and `build.rs` generates the [`PLANS`]
//! registry from them.  The filename stem is the plan `id`: the stable
//! serialization key, and the name a profile lists in `band_plans = [...]`
//! to put it in that build's Band Plan menu.  Add a plan = drop a `.toml` in
//! `band_plans/`.
//!
//! [`BandPlan`] is an index into [`PLANS`].  A persisted selection is stored
//! by a hash of the plan `id` (see [`band_plan_storage_id`]) so it survives
//! plans being added/reordered, rather than by array position.
//!
//! ## Why band plans matter
//!
//! At a venue running pro wireless mics/IEMs, the audio engineer coordinates
//! frequencies to avoid third-order intermodulation.  Picking a plan that
//! aligns with the venue's gear (e.g. the Shure G58 / Sennheiser A1 plans)
//! keeps an OpenStageRF link coordinated with that ecosystem.

use heapless::String;

/// One channel within a band plan.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ChannelInfo {
    /// Short label shown in lists (≤ 4 chars, e.g. `"01"`).
    pub label: &'static str,
    /// Absolute frequency in kHz.  `915_000` = 915.000 MHz.
    pub frequency_khz: u32,
}

impl ChannelInfo {
    /// Format the frequency as `"915.000 MHz"` etc.
    pub fn format_frequency(&self) -> String<16> {
        let mhz_int = self.frequency_khz / 1000;
        let mhz_frac = self.frequency_khz % 1000;
        let mut out: String<16> = String::new();
        use core::fmt::Write as _;
        let _ = write!(&mut out, "{}.{:03} MHz", mhz_int, mhz_frac);
        out
    }
}

/// One band plan: a stable `id`, a display `label`, and a channel list.
/// Built from `band_plans/<id>.toml` by `build.rs`.
#[derive(Debug, Clone, Copy)]
pub struct BandPlanInfo {
    /// Stable identifier (the TOML filename stem).  Serialization key +
    /// the name profiles list in `band_plans = [...]`.
    pub id: &'static str,
    /// Short label shown in the Band Plan list / Idle banner (≤ 12 chars).
    pub label: &'static str,
    /// Channel list.  Index 0 is the default channel for this plan.
    pub channels: &'static [ChannelInfo],
}

/// Identifier for a band plan: an index into [`PLANS`].  Small + `Copy` so
/// it lives cheaply in [`crate::Settings`].  Persisted via
/// [`band_plan_storage_id`] (an id hash), not this index.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
pub struct BandPlan(pub u16);

// Generated by build.rs from band_plans/*.toml (sorted by id):
//   PLANS: &[BandPlanInfo]      — the registry; BandPlan(i) -> PLANS[i]
//   BAND_PLANS: &[BandPlan]     — every plan, in id order
//   DEFAULT_BAND_PLAN: BandPlan — the `ism915` plan (else first)
include!(concat!(env!("OUT_DIR"), "/band_plans_generated.rs"));

impl BandPlan {
    /// The static info for this plan.
    pub fn info(self) -> &'static BandPlanInfo {
        &PLANS[self.0 as usize]
    }
    /// Stable string id (the TOML filename stem).
    pub fn id(self) -> &'static str {
        self.info().id
    }
}

impl Default for BandPlan {
    fn default() -> Self {
        DEFAULT_BAND_PLAN
    }
}

/// Look up a plan by its stable `id` (e.g. `"ism915"`, `"shure_g58_g1"`).
pub fn plan_by_id(id: &str) -> Option<BandPlan> {
    (0..PLANS.len())
        .map(|i| BandPlan(i as u16))
        .find(|p| p.id() == id)
}

/// Look up a channel within a band plan by index, clamping to range.
pub fn channel(plan: BandPlan, idx: u8) -> ChannelInfo {
    let info = plan.info();
    let i = (idx as usize).min(info.channels.len().saturating_sub(1));
    info.channels[i]
}

/// Maximum channel index for a band plan (0-based).
pub fn max_channel_index(plan: BandPlan) -> u8 {
    plan.info().channels.len().saturating_sub(1) as u8
}

/// FNV-1a hash of a plan id — the value persisted for a selected plan.
/// Stable across plans being added/reordered (unlike an array index), so a
/// saved selection survives registry changes.
const fn id_hash(s: &str) -> u32 {
    let b = s.as_bytes();
    let mut h: u32 = 0x811c_9dc5;
    let mut i = 0;
    while i < b.len() {
        h ^= b[i] as u32;
        h = h.wrapping_mul(0x0100_0193);
        i += 1;
    }
    h
}

/// Value to persist for a selected plan (a hash of its id).
pub fn band_plan_storage_id(plan: BandPlan) -> u32 {
    id_hash(plan.id())
}

/// Resolve a persisted [`band_plan_storage_id`] back to a plan, if it still
/// exists in this build's registry.
pub fn band_plan_from_storage_id(stored: u32) -> Option<BandPlan> {
    (0..PLANS.len())
        .map(|i| BandPlan(i as u16))
        .find(|p| id_hash(p.id()) == stored)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn all_plans_have_at_least_one_channel() {
        for &p in BAND_PLANS {
            assert!(
                !p.info().channels.is_empty(),
                "plan {:?} has no channels",
                p.id()
            );
        }
    }

    #[test]
    fn channel_label_fits_in_4_chars() {
        for &p in BAND_PLANS {
            for c in p.info().channels {
                assert!(c.label.len() <= 4, "label too long: {:?}", c.label);
            }
        }
    }

    #[test]
    fn frequencies_in_supported_band() {
        // Every channel must sit in a band we support: 470–514 MHz
        // (CN470/SX1268) or 902–928 MHz US ISM (SX1262).
        for &p in BAND_PLANS {
            for c in p.info().channels {
                let in_470 = (470_000..=516_000).contains(&c.frequency_khz);
                let in_ism = (902_000..=928_000).contains(&c.frequency_khz);
                assert!(
                    in_470 || in_ism,
                    "channel {:?} of plan {:?} at {} kHz is outside every supported band",
                    c.label,
                    p.id(),
                    c.frequency_khz
                );
            }
        }
    }

    #[test]
    fn ids_unique_and_hash_collision_free() {
        // Storage relies on id hashes being distinct.
        for (i, a) in BAND_PLANS.iter().enumerate() {
            for b in &BAND_PLANS[i + 1..] {
                assert_ne!(a.id(), b.id(), "duplicate plan id {:?}", a.id());
                assert_ne!(
                    band_plan_storage_id(*a),
                    band_plan_storage_id(*b),
                    "id hash collision: {:?} vs {:?}",
                    a.id(),
                    b.id()
                );
            }
        }
    }

    #[test]
    fn storage_id_round_trips() {
        for &p in BAND_PLANS {
            let stored = band_plan_storage_id(p);
            assert_eq!(band_plan_from_storage_id(stored), Some(p));
        }
    }

    #[test]
    fn format_frequency_renders_three_decimals() {
        let c = ChannelInfo {
            label: "x",
            frequency_khz: 915_000,
        };
        assert_eq!(c.format_frequency().as_str(), "915.000 MHz");
        let c = ChannelInfo {
            label: "x",
            frequency_khz: 916_125,
        };
        assert_eq!(c.format_frequency().as_str(), "916.125 MHz");
    }

    #[test]
    fn channel_lookup_clamps_overflow() {
        let ism = plan_by_id("ism915").expect("ism915 plan present");
        let c = channel(ism, 99);
        assert_eq!(c.label, "24"); // last of ISM 915's 24 channels
    }
}
