// SPDX-License-Identifier: AGPL-3.0-or-later
#![no_std]

// Shared MIDI-node application logic.
// Platform entry points live in src/bin/; shared code goes here.

// Profile configuration generated by `cargo xtask build <profile>`.
// Contains DIVERSITY_MODE, NUM_RADIOS, and (for dual_spi modes) a radio1 module
// with peripheral type aliases.  Bin files that need diversity config import
// from here: `use osrf_app_midi_node::profile_config`.
#[allow(dead_code)]
pub mod profile_config {
    include!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/src/generated/profile_config.rs"
    ));
}
