// SPDX-License-Identifier: AGPL-3.0-or-later
#![no_std]
#![no_main]

//! Generic T114 UI binary. The role / tx_source / diversity / band are
//! baked in at build time from a `configs/<name>.toml` profile (selected via
//! the `OSRF_PROFILE` env var by the xtask) — see `build.rs`. Flash with
//! `cargo xtask run <profile>`; all UI / link / soft-off logic lives in the
//! `osrf_profile_t114_ui` library.

use defmt_rtt as _;
use embassy_executor::Spawner;
use osrf_board_t114 as board;
use osrf_profile_t114_ui::run;

// Generated by build.rs: ROLE, TX_SOURCE, DIVERSITY, BAND_PLANS,
// POWER_POLICY, CHEMISTRY, NAME.
include!(concat!(env!("OUT_DIR"), "/config.rs"));

#[cortex_m_rt::pre_init]
unsafe fn pre_init() {
    board::bootloader_handoff();
}

#[embassy_executor::main]
async fn main(spawner: Spawner) {
    run(
        spawner,
        ROLE,
        TX_SOURCE,
        DIVERSITY,
        BAND_PLANS,
        POWER_POLICY,
        CHEMISTRY,
        NAME,
    )
    .await;
}
