// SPDX-License-Identifier: AGPL-3.0-or-later
#![no_std]
#![no_main]

//! Milestone 6 UI smoke test, T114 deployment.
//!
//! Brings up:
//!   - ST7789 TFT (board crate's hand-rolled driver)
//!   - 5-way joystick on `joystick` pins per the board crate
//!     (Up=P1_14, Right=P1_12, Left=P0_07, Down=P0_08, Center=P0_13).
//!     Wired active-low: COMMON to GND, each direction terminal to
//!     its GPIO pin, internal pull-ups holding idle HIGH.
//!   - Edge-wake joystick driver from `osrf-driver-input-joystick5way`.
//!   - `osrf-ui` state machine + renderer.
//!
//! Two cooperating tasks:
//!   - `joystick_task` waits for joystick events and feeds them
//!     into a [`Channel`].
//!   - The main task awaits the channel, runs `UiState::handle_event`,
//!     re-renders, and logs any [`Command`] for debugging (no live
//!     link wiring yet — that lands when we plumb a config-update
//!     signal into `osrf-link-runtime`).

use defmt_rtt as _;
use embassy_executor::Spawner;
use embassy_sync::blocking_mutex::raw::CriticalSectionRawMutex;
use embassy_sync::channel::Channel;
use embedded_graphics_core::pixelcolor::Rgb565;
use embedded_graphics_core::prelude::*;
use embedded_graphics_core::primitives::Rectangle;
use embedded_graphics_core::Pixel;
use osrf_board_t114 as board;
use osrf_driver_input_joystick5way::{Joystick5Way, JoystickEvent};
use osrf_ui::{build_screen, KeyStore, LinkStatus, Renderer, Settings, UiState, WidgetList};
use panic_probe as _;

use board::embassy_nrf::gpio::{Input, Pull};

/// Joystick pin types per `boards/t114/src/lib.rs::joystick`.
type Joystick = Joystick5Way<
    Input<'static>,
    Input<'static>,
    Input<'static>,
    Input<'static>,
    Input<'static>,
>;

/// Input event channel — joystick task pushes, main task pops.
/// Capacity 8: more than enough for human input rates.
static EVENT_CHAN: Channel<CriticalSectionRawMutex, JoystickEvent, 8> = Channel::new();

/// Newtype wrapper for `board::Display` so `render` (generic over
/// `DrawTarget`) can be called without orphan-rule concerns.
struct DisplayTarget(board::Display);

impl Dimensions for DisplayTarget {
    fn bounding_box(&self) -> Rectangle {
        self.0.bounding_box()
    }
}

impl DrawTarget for DisplayTarget {
    type Color = Rgb565;
    type Error = <board::Display as DrawTarget>::Error;
    fn draw_iter<I>(&mut self, pixels: I) -> Result<(), Self::Error>
    where
        I: IntoIterator<Item = Pixel<Self::Color>>,
    {
        self.0.draw_iter(pixels)
    }
    fn fill_contiguous<I>(&mut self, area: &Rectangle, colors: I) -> Result<(), Self::Error>
    where
        I: IntoIterator<Item = Self::Color>,
    {
        self.0.fill_contiguous(area, colors)
    }
    fn fill_solid(&mut self, area: &Rectangle, color: Self::Color) -> Result<(), Self::Error> {
        self.0.fill_solid(area, color)
    }
    fn clear(&mut self, color: Self::Color) -> Result<(), Self::Error> {
        self.0.clear(color)
    }
}

#[cortex_m_rt::pre_init]
unsafe fn pre_init() {
    board::bootloader_handoff();
}

#[embassy_executor::main]
async fn main(spawner: Spawner) {
    let mut r = board::resources();

    defmt::info!("ui (T114): bringing up display + joystick");

    // ── Display ─────────────────────────────────────────────────────────────
    r.display.init().await;
    let mut display = DisplayTarget(r.display);
    r.display_backlight.set_low(); // backlight on (active LOW)

    // ── Joystick ────────────────────────────────────────────────────────────
    // Claim the joystick pins directly (the board crate's
    // `Resources` doesn't own them — joystick is an external add-on
    // wired to the P1 header).
    let pins = unsafe {
        use board::embassy_nrf::peripherals::*;
        (
            P1_14::steal(), // Up
            P0_08::steal(), // Down
            P0_07::steal(), // Left
            P1_12::steal(), // Right
            P0_13::steal(), // Center
        )
    };
    let js_up = Input::new(pins.0, Pull::Up);
    let js_dn = Input::new(pins.1, Pull::Up);
    let js_lt = Input::new(pins.2, Pull::Up);
    let js_rt = Input::new(pins.3, Pull::Up);
    let js_ct = Input::new(pins.4, Pull::Up);
    let joystick = Joystick5Way::new(js_up, js_dn, js_lt, js_rt, js_ct);
    spawner.spawn(joystick_task(joystick).unwrap());

    // ── UI state ────────────────────────────────────────────────────────────
    let mut state = UiState::default();
    let mut settings = Settings::default();
    // Seed the key store with placeholder entries baked into the
    // firmware.  AEAD isn't implemented yet (Stage 3 in
    // ROADMAP.md), so these are name + fingerprint only — no key
    // material.  When AEAD lands and `KeyEntry` grows a key-bytes
    // field, replace these with real keys generated by a
    // user-side keygen tool, or load from a flash partition.
    //
    // The fingerprints chosen here are arbitrary 24-bit values.
    // The on-wire `key_fp` header field uses the low 24 bits of
    // each fingerprint; `0x000000` is reserved for the open
    // (no-encryption) path so neither value here may be zero.
    let mut keys = KeyStore::new();
    let _ = keys.add("Studio A", 0x111111);
    let _ = keys.add("Backup",   0x222222);
    let status = LinkStatus::default(); // no link wired yet — stub
    let mut widgets: WidgetList = WidgetList::new();
    let mut renderer = Renderer::new();

    // Initial paint.  First call triggers a full clear (so we don't
    // paint over panel-RAM garbage); subsequent calls only touch
    // changed rows.
    build_screen(&state, &settings, &keys, &status, &mut widgets);
    let _ = renderer.render(&widgets, &mut display);

    defmt::info!("ui ready: screen={:?}", state.screen);

    loop {
        let event = EVENT_CHAN.receive().await;
        defmt::info!("event: {:?}", event);
        if let Some(cmd) = state.handle_event(&mut settings, &keys, event) {
            defmt::info!("command: {:?}", cmd);
            // TODO: forward to link runtime via config-update signal.
        }
        defmt::info!(
            "state: screen={:?} cursor={} edit={}",
            state.screen,
            state.cursor,
            state.edit_mode
        );
        build_screen(&state, &settings, &keys, &status, &mut widgets);
        let _ = renderer.render(&widgets, &mut display);
    }
}

/// Joystick poll/wake task.  Owns the `Joystick5Way` driver, awaits
/// events, and forwards them to the main task via [`EVENT_CHAN`].
#[embassy_executor::task]
async fn joystick_task(mut js: Joystick) {
    loop {
        let ev = js.next_event().await;
        EVENT_CHAN.send(ev).await;
    }
}
