// SPDX-License-Identifier: AGPL-3.0-or-later
#![no_std]
#![no_main]

//! Milestone 6 UI smoke test, T114 deployment.
//!
//! Brings up:
//!   - ST7789 TFT (board crate's hand-rolled driver)
//!   - 5-way joystick on `joystick` pins per the board crate
//!     (Up=P1_14, Right=P1_12, Left=P0_07, Down=P0_08, Center=P0_13).
//!     Wired active-low: COMMON to GND, each direction terminal to
//!     its GPIO pin, internal pull-ups holding idle HIGH.
//!   - Edge-wake joystick driver from `osrf-driver-input-joystick5way`.
//!   - `osrf-ui` state machine + renderer.
//!
//! Two cooperating tasks:
//!   - `joystick_task` waits for joystick events and feeds them
//!     into a [`Channel`].
//!   - The main task awaits the channel, runs `UiState::handle_event`,
//!     re-renders, and logs any [`Command`] for debugging (no live
//!     link wiring yet — that lands when we plumb a config-update
//!     signal into `osrf-link-runtime`).

use defmt_rtt as _;
use embassy_executor::Spawner;
use embassy_futures::select::{select, Either};
use embassy_sync::blocking_mutex::raw::CriticalSectionRawMutex;
use embassy_sync::channel::Channel;
use embassy_time::{Duration, Instant, Timer};
use embedded_graphics_core::pixelcolor::Rgb565;
use embedded_graphics_core::prelude::*;
use embedded_graphics_core::primitives::Rectangle;
use embedded_graphics_core::Pixel;
use osrf_board_t114 as board;
use osrf_driver_input_joystick5way::{Joystick5Way, JoystickEvent};
use osrf_ui::{
    build_screen, KeyStore, LinkStatus, Renderer, ScreenId, Settings, UiState, WidgetList,
    MAX_SCAN_CHANNELS,
};
use panic_probe as _;

use board::embassy_nrf::gpio::{Input, Pull};

/// Joystick pin types per `boards/t114/src/lib.rs::joystick`.
type Joystick = Joystick5Way<
    Input<'static>,
    Input<'static>,
    Input<'static>,
    Input<'static>,
    Input<'static>,
>;

/// Input event channel — joystick task pushes, main task pops.
/// Capacity 8: more than enough for human input rates.
static EVENT_CHAN: Channel<CriticalSectionRawMutex, JoystickEvent, 8> = Channel::new();

/// Newtype wrapper for `board::Display` so `render` (generic over
/// `DrawTarget`) can be called without orphan-rule concerns.
struct DisplayTarget(board::Display);

impl Dimensions for DisplayTarget {
    fn bounding_box(&self) -> Rectangle {
        self.0.bounding_box()
    }
}

impl DrawTarget for DisplayTarget {
    type Color = Rgb565;
    type Error = <board::Display as DrawTarget>::Error;
    fn draw_iter<I>(&mut self, pixels: I) -> Result<(), Self::Error>
    where
        I: IntoIterator<Item = Pixel<Self::Color>>,
    {
        self.0.draw_iter(pixels)
    }
    fn fill_contiguous<I>(&mut self, area: &Rectangle, colors: I) -> Result<(), Self::Error>
    where
        I: IntoIterator<Item = Self::Color>,
    {
        self.0.fill_contiguous(area, colors)
    }
    fn fill_solid(&mut self, area: &Rectangle, color: Self::Color) -> Result<(), Self::Error> {
        self.0.fill_solid(area, color)
    }
    fn clear(&mut self, color: Self::Color) -> Result<(), Self::Error> {
        self.0.clear(color)
    }
}

#[cortex_m_rt::pre_init]
unsafe fn pre_init() {
    board::bootloader_handoff();
}

#[embassy_executor::main]
async fn main(spawner: Spawner) {
    let mut r = board::resources();

    defmt::info!("ui (T114): bringing up display + joystick");

    // ── Display ─────────────────────────────────────────────────────────────
    r.display.init().await;
    let mut display = DisplayTarget(r.display);
    r.display_backlight.set_low(); // backlight on (active LOW)

    // ── Joystick ────────────────────────────────────────────────────────────
    // Claim the joystick pins directly (the board crate's
    // `Resources` doesn't own them — joystick is an external add-on
    // wired to the P1 header).
    let pins = unsafe {
        use board::embassy_nrf::peripherals::*;
        (
            P1_14::steal(), // Up
            P0_08::steal(), // Down
            P0_07::steal(), // Left
            P1_12::steal(), // Right
            P0_13::steal(), // Center
        )
    };
    let js_up = Input::new(pins.0, Pull::Up);
    let js_dn = Input::new(pins.1, Pull::Up);
    let js_lt = Input::new(pins.2, Pull::Up);
    let js_rt = Input::new(pins.3, Pull::Up);
    let js_ct = Input::new(pins.4, Pull::Up);
    let joystick = Joystick5Way::new(js_up, js_dn, js_lt, js_rt, js_ct);
    spawner.spawn(joystick_task(joystick).unwrap());

    // ── UI state ────────────────────────────────────────────────────────────
    let mut state = UiState::default();
    let mut settings = Settings::default();
    // Seed the key store with placeholder entries baked into the
    // firmware.  AEAD isn't implemented yet (Stage 3 in
    // ROADMAP.md), so these are name + fingerprint only — no key
    // material.  When AEAD lands and `KeyEntry` grows a key-bytes
    // field, replace these with real keys generated by a
    // user-side keygen tool, or load from a flash partition.
    //
    // The fingerprints chosen here are arbitrary 24-bit values.
    // The on-wire `key_fp` header field uses the low 24 bits of
    // each fingerprint; `0x000000` is reserved for the open
    // (no-encryption) path so neither value here may be zero.
    let mut keys = KeyStore::new();
    let _ = keys.add("Studio A", 0x111111);
    let _ = keys.add("Backup",   0x222222);
    let status = LinkStatus::default(); // no link wired yet — stub
    let mut widgets: WidgetList = WidgetList::new();
    let mut renderer = Renderer::new();

    // Initial paint.  First call triggers a full clear (so we don't
    // paint over panel-RAM garbage); subsequent calls only touch
    // changed rows.
    build_screen(&state, &settings, &keys, &status, &mut widgets);
    let _ = renderer.render(&widgets, &state.scan, &mut display);

    defmt::info!("ui ready: screen={:?}", state.screen);

    // Scan tick interval — how often we synthesize a scan pass
    // while on the Scan screen.  300 ms is a hand-feel-good rate
    // for the bars to update visibly without thrashing the
    // renderer.  The real scanner (once wired) will take roughly
    // `channels × 12 ms` per pass, so 300 ms is a generous
    // ceiling for the 24-channel ISM 915 plan.
    let scan_tick = Duration::from_millis(300);

    loop {
        let next_tick = Timer::after(scan_tick);
        match select(EVENT_CHAN.receive(), next_tick).await {
            Either::First(event) => {
                defmt::info!("event: {:?}", event);
                if let Some(cmd) = state.handle_event(&mut settings, &keys, event) {
                    defmt::info!("command: {:?}", cmd);
                    // TODO: forward to link runtime via config-update signal.
                }
                defmt::info!(
                    "state: screen={:?} cursor={} edit={}",
                    state.screen,
                    state.cursor,
                    state.edit_mode
                );
            }
            Either::Second(()) => {
                // Periodic tick.  Only doing scan work on the
                // Scan screen; no-op everywhere else.  When the
                // real `RssiScanner` lands, this is where
                // `link_runtime.scan_step(...)` gets called.
                if state.screen == ScreenId::Scan {
                    let mut buf = [0i16; MAX_SCAN_CHANNELS];
                    let n = state.scan.channel_count as usize;
                    synth_scan_pass(&mut buf[..n]);
                    state.apply_scan_pass(&buf[..n]);
                }
            }
        }
        build_screen(&state, &settings, &keys, &status, &mut widgets);
        let _ = renderer.render(&widgets, &state.scan, &mut display);
    }
}

/// Stub scanner: synthesize per-channel noise floors that move
/// over time so the Scan screen visibly updates without a real
/// radio.  Each channel oscillates around its own baseline at a
/// distinct phase, with one occasional spike per pass to exercise
/// the peak-tick render path.  Replace with a real
/// `link_runtime.scan_step(...)` call once live config-update
/// plumbing lands.
fn synth_scan_pass(out: &mut [i16]) {
    let n = out.len();
    let t = Instant::now().as_millis() as i32;
    let spike_target = (t / 600) as usize % n.max(1);
    for (i, slot) in out.iter_mut().enumerate() {
        // Triangle wave per channel, period ~6 s, amplitude 12 dB.
        let phase = ((t / 50) + (i as i32) * 30) % 240;
        let tri = if phase < 120 { phase } else { 240 - phase }; // 0..120
        let baseline = -100 - (i as i32 % 5); // -100..-104 dBm baseline
        let mut dbm = baseline + (tri / 10); // ±12 dB swing
        if spike_target == i {
            dbm += 18;
        }
        *slot = dbm as i16;
    }
}

/// Joystick poll/wake task.  Owns the `Joystick5Way` driver, awaits
/// events, and forwards them to the main task via [`EVENT_CHAN`].
#[embassy_executor::task]
async fn joystick_task(mut js: Joystick) {
    loop {
        let ev = js.next_event().await;
        EVENT_CHAN.send(ev).await;
    }
}
