// SPDX-License-Identifier: AGPL-3.0-or-later
//! Bakes a deployment profile into the firmware at build time.
//!
//! Reads the TOML file named by the `OSRF_PROFILE` env var (set by the
//! xtask from `configs/<name>.toml`) and emits `$OUT_DIR/config.rs` with the
//! `ROLE` / `TX_SOURCE` / `DIVERSITY` / `BAND_PLANS` constants that
//! `src/main.rs` `include!`s and passes to `t114_ui::run`.  With no
//! `OSRF_PROFILE` set it builds a default (rx / 915) and warns — use
//! `cargo xtask run <profile>` for a real build.
use std::env;
use std::fs;
use std::path::PathBuf;

fn main() {
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-env-changed=OSRF_PROFILE");

    let mut role = String::from("rx");
    let mut tx_source = String::from("uart");
    let mut diversity = false;
    let mut band = String::from("915");

    match env::var_os("OSRF_PROFILE") {
        Some(p) => {
            let path = PathBuf::from(p);
            println!("cargo:rerun-if-changed={}", path.display());
            let text = fs::read_to_string(&path)
                .unwrap_or_else(|e| panic!("OSRF_PROFILE {}: {e}", path.display()));
            let t: toml::Table = text
                .parse()
                .unwrap_or_else(|e| panic!("{}: invalid TOML: {e}", path.display()));
            if let Some(v) = t.get("role").and_then(|v| v.as_str()) {
                role = v.to_string();
            }
            if let Some(v) = t.get("tx_source").and_then(|v| v.as_str()) {
                tx_source = v.to_string();
            }
            if let Some(v) = t.get("diversity").and_then(|v| v.as_bool()) {
                diversity = v;
            }
            if let Some(v) = t.get("band").and_then(|v| v.as_str()) {
                band = v.to_string();
            }
        }
        None => {
            println!(
                "cargo:warning=OSRF: OSRF_PROFILE not set — building default (rx, 915 MHz). \
                 Flash a real profile with `cargo xtask run <profile>`."
            );
        }
    }

    let role_v = match role.as_str() {
        "tx" => "Tx",
        "rx" => "Rx",
        o => panic!("profile `role` must be \"tx\" or \"rx\", got {o:?}"),
    };
    let tx_v = match tx_source.as_str() {
        "uart" => "Uart",
        "scenario" => "Scenario",
        o => panic!("profile `tx_source` must be \"uart\" or \"scenario\", got {o:?}"),
    };
    let band_v = match band.as_str() {
        "915" => "BAND_PLANS_915",
        "470" => "BAND_PLANS_470",
        o => panic!("profile `band` must be \"915\" or \"470\", got {o:?}"),
    };

    let generated = format!(
        "// @generated by build.rs from OSRF_PROFILE\n\
         const ROLE: osrf_ui::Role = osrf_ui::Role::{role_v};\n\
         const TX_SOURCE: osrf_profile_t114_ui::TxSource = osrf_profile_t114_ui::TxSource::{tx_v};\n\
         const DIVERSITY: bool = {diversity};\n\
         const BAND_PLANS: &[osrf_ui::BandPlan] = osrf_ui::{band_v};\n",
    );
    let out = PathBuf::from(env::var_os("OUT_DIR").unwrap());
    fs::write(out.join("config.rs"), generated).unwrap();
}
