[package]
name    = "osrf-radio-sx126x"
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0-or-later"

[features]
defmt = ["dep:defmt", "sx1262/defmt"]

[dependencies]
defmt              = { workspace = true, optional = true }
embedded-hal       = { workspace = true }
embedded-hal-async = { workspace = true }
heapless           = { workspace = true }
sx1262             = { version = "0.3", default-features = false }

[lib]
test    = false
doctest = false
bench   = false
