// SPDX-License-Identifier: AGPL-3.0-or-later
//! Generates the band-plan registry from `band_plans/*.toml`.
//!
//! Each `band_plans/<id>.toml` is one plan (`label` + `channels_khz`); the
//! filename stem is the plan `id` (the stable serialization key and the name
//! profiles list in their `band_plans = [...]`).  This emits
//! `$OUT_DIR/band_plans_generated.rs` with `PLANS` (sorted by id — the index
//! space `BandPlan` wraps), `BAND_PLANS` (every plan), and
//! `DEFAULT_BAND_PLAN`.  Plans are kept in lexicographic id order so this and
//! the app crate's profile-menu build.rs agree on indices.
use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    let manifest = env::var("CARGO_MANIFEST_DIR").unwrap();
    let dir = Path::new(&manifest).join("../../band_plans");
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed={}", dir.display());

    // Collect (id, label, channels) sorted by id (= filename stem).
    let mut entries: Vec<(String, String, Vec<u32>)> = Vec::new();
    let mut files: Vec<PathBuf> = fs::read_dir(&dir)
        .unwrap_or_else(|e| panic!("cannot read {}: {e}", dir.display()))
        .filter_map(|e| e.ok().map(|e| e.path()))
        .filter(|p| p.extension().and_then(|x| x.to_str()) == Some("toml"))
        .collect();
    files.sort();
    for path in &files {
        println!("cargo:rerun-if-changed={}", path.display());
        let id = path.file_stem().unwrap().to_str().unwrap().to_string();
        let text = fs::read_to_string(path).unwrap();
        let t: toml::Table = text
            .parse()
            .unwrap_or_else(|e| panic!("{}: invalid TOML: {e}", path.display()));
        let label = t
            .get("label")
            .and_then(|v| v.as_str())
            .unwrap_or_else(|| panic!("{}: missing `label`", path.display()))
            .to_string();
        let chans: Vec<u32> = t
            .get("channels_khz")
            .and_then(|v| v.as_array())
            .unwrap_or_else(|| panic!("{}: missing `channels_khz` array", path.display()))
            .iter()
            .map(|v| {
                u32::try_from(v.as_integer().expect("channel must be an integer kHz"))
                    .expect("channel kHz out of u32 range")
            })
            .collect();
        assert!(!chans.is_empty(), "{}: empty channel list", path.display());
        entries.push((id, label, chans));
    }
    assert!(
        !entries.is_empty(),
        "no band_plans/*.toml found in {}",
        dir.display()
    );

    let default_idx = entries
        .iter()
        .position(|(id, _, _)| id == "ism915")
        .unwrap_or(0);

    let mut out = String::from("// @generated by build.rs from band_plans/*.toml\n");
    out.push_str("pub const PLANS: &[BandPlanInfo] = &[\n");
    for (id, label, chans) in &entries {
        // Channel labels: zero-padded sequence, ≤4 chars (3 digits past 99).
        let width = (chans.len().to_string().len()).max(2);
        out.push_str(&format!(
            "    BandPlanInfo {{ id: {id:?}, label: {label:?}, channels: &[\n"
        ));
        for (i, khz) in chans.iter().enumerate() {
            out.push_str(&format!(
                "        ChannelInfo {{ label: \"{:0width$}\", frequency_khz: {khz} }},\n",
                i + 1
            ));
        }
        out.push_str("    ] },\n");
    }
    out.push_str("];\n\n");

    out.push_str("pub const BAND_PLANS: &[BandPlan] = &[\n");
    for i in 0..entries.len() {
        out.push_str(&format!("    BandPlan({i}),\n"));
    }
    out.push_str("];\n\n");
    out.push_str(&format!(
        "/// Boot/fallback default (the `ism915` plan, else the first plan).\n\
         pub const DEFAULT_BAND_PLAN: BandPlan = BandPlan({default_idx});\n"
    ));

    let out_dir = PathBuf::from(env::var_os("OUT_DIR").unwrap());
    fs::write(out_dir.join("band_plans_generated.rs"), out).unwrap();
}
