// SPDX-License-Identifier: AGPL-3.0-or-later
//! Bakes a keyring of AEAD keys into the firmware at build time.
//!
//! Reads a TOML key file (default: `<workspace>/osrf-keys.toml`, override
//! with the `OSRF_KEYS_FILE` env var) and emits `$OUT_DIR/keys.rs` with a
//! `BAKED_KEYS` slice that `src/lib.rs` registers into the runtime keystore
//! (all entries show up in the Key menu).  If the file is absent the build
//! still succeeds using built-in TEST keys, with a loud `cargo:warning`.
//!
//! File format — each top-level table is one key (the table name is the
//! default display name; `name =` overrides it):
//! ```toml
//! device_id = 1            # u32; paired units must match
//! active    = "SchoolZone" # optional: which key is selected at boot
//!
//! [SchoolZone]
//! hex = "<64 hex chars = 32 bytes>"
//!
//! [Backup]
//! name = "Backup Key"      # optional display-name override
//! hex  = "<64 hex chars>"
//! ```
//! Both paired units must build with (and select) the same key.
use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-env-changed=OSRF_KEYS_FILE");

    let manifest = env::var("CARGO_MANIFEST_DIR").unwrap();
    let key_path = env::var_os("OSRF_KEYS_FILE")
        .map(PathBuf::from)
        .unwrap_or_else(|| Path::new(&manifest).join("../../osrf-keys.toml"));
    println!("cargo:rerun-if-changed={}", key_path.display());

    // (display-name, 32-byte key) pairs.
    let mut keys: Vec<(String, [u8; 32])> = Vec::new();
    let mut device_id: u32 = 1;
    let mut active: Option<String> = None;

    match fs::read_to_string(&key_path) {
        Ok(content) => {
            let tbl: toml::Table = content
                .parse()
                .unwrap_or_else(|e| panic!("{}: invalid TOML: {e}", key_path.display()));
            if let Some(v) = tbl.get("device_id").and_then(|v| v.as_integer()) {
                device_id = u32::try_from(v)
                    .unwrap_or_else(|_| panic!("{}: device_id out of u32 range", key_path.display()));
            }
            active = tbl.get("active").and_then(|v| v.as_str()).map(String::from);
            // Every other top-level table is a key.
            for (table_name, val) in &tbl {
                if matches!(table_name.as_str(), "device_id" | "active") {
                    continue;
                }
                let Some(t) = val.as_table() else {
                    println!(
                        "cargo:warning=OSRF: {} top-level `{table_name}` is not a key table — ignored.",
                        key_path.display()
                    );
                    continue;
                };
                let display = t
                    .get("name")
                    .and_then(|v| v.as_str())
                    .unwrap_or(table_name)
                    .to_string();
                keys.push((display, parse_hex32(t, table_name, &key_path)));
            }
            if keys.is_empty() {
                println!(
                    "cargo:warning=OSRF: {} has no key tables — baking TEST keys. NOT FOR PRODUCTION.",
                    key_path.display()
                );
                keys = test_keys();
            }
        }
        Err(_) => {
            println!(
                "cargo:warning=OSRF: no key file at {} (set OSRF_KEYS_FILE or create osrf-keys.toml) — \
                 baking TEST keys [0x42;32]/[0x99;32]. NOT FOR PRODUCTION.",
                key_path.display()
            );
            keys = test_keys();
        }
    }

    // Resolve the boot-default key index from `active` (by display name).
    let active_idx: Option<usize> = match &active {
        Some(name) => {
            let idx = keys.iter().position(|(n, _)| n == name);
            if idx.is_none() {
                println!(
                    "cargo:warning=OSRF: {}: active = {name:?} matches no key — booting in Open mode.",
                    key_path.display()
                );
            }
            idx
        }
        // No explicit `active`: default to the first key so a freshly-flashed
        // device comes up encrypted rather than in the clear.
        None => (!keys.is_empty()).then_some(0),
    };

    let mut entries = String::new();
    for (name, key) in &keys {
        entries.push_str(&format!("    ({name:?}, {}),\n", byte_array_literal(key)));
    }
    let active_lit = match active_idx {
        Some(i) => format!("Some({i})"),
        None => String::from("None"),
    };
    let generated = format!(
        "// @generated by build.rs from {path}\n\
         const KEY_DEVICE_ID: u32 = {device_id};\n\
         /// (display-name, 32-byte key) — all registered in the Key menu.\n\
         const BAKED_KEYS: &[(&str, [u8; 32])] = &[\n{entries}];\n\
         /// Index into `BAKED_KEYS` of the boot-default key, or `None` for Open.\n\
         const ACTIVE_KEY_IDX: Option<usize> = {active_lit};\n",
        path = key_path.display(),
    );
    let out = PathBuf::from(env::var_os("OUT_DIR").unwrap());
    fs::write(out.join("keys.rs"), generated).unwrap();
}

/// Historical built-in test keys (used when no key file is present).
fn test_keys() -> Vec<(String, [u8; 32])> {
    vec![
        (String::from("Shared"), [0x42u8; 32]),
        (String::from("TX-Only"), [0x99u8; 32]),
    ]
}

/// Parse a `hex = "..."` field (64 hex chars) from a key table.
fn parse_hex32(t: &toml::Table, slot: &str, path: &Path) -> [u8; 32] {
    let hex = t
        .get("hex")
        .and_then(|v| v.as_str())
        .unwrap_or_else(|| panic!("{}: [{slot}] missing `hex`", path.display()))
        .trim();
    assert_eq!(
        hex.len(),
        64,
        "{}: [{slot}].hex must be 64 hex chars (32 bytes), got {}",
        path.display(),
        hex.len()
    );
    let mut out = [0u8; 32];
    for (i, b) in out.iter_mut().enumerate() {
        *b = u8::from_str_radix(&hex[i * 2..i * 2 + 2], 16)
            .unwrap_or_else(|_| panic!("{}: [{slot}].hex has non-hex characters", path.display()));
    }
    out
}

fn byte_array_literal(b: &[u8; 32]) -> String {
    let mut s = String::from("[");
    for (i, x) in b.iter().enumerate() {
        if i > 0 {
            s.push_str(", ");
        }
        s.push_str(&format!("0x{x:02x}"));
    }
    s.push(']');
    s
}
